//! Witt classes of finite quadratic modules.
//!
//! This is the Wall/Nikulin finite-module side of the integral pillar: a
//! nonsingular finite quadratic module is reduced, prime by prime, by quotienting
//! isotropic cyclic subgroups until an anisotropic core remains. The terminal core
//! is canonicalised as a finite table, so the output is a full Witt normal form,
//! not just the Milgram/Brown phase.

use crate::forms::integral::discriminant::{phase_mod8_from_q_values, DiscriminantForm, IsoTables};
use crate::scalar::{Rational, Scalar};
use std::collections::{BTreeMap, BTreeSet, VecDeque};

const FQM_WITT_GROUP_CAP: usize = 512;
const FQM_WITT_TUPLE_CAP: u128 = 2_000_000;

/// A value-count entry in a finite quadratic module normal form.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FqmValueCount {
    /// Numerator of the canonical rational representative.
    pub numer: i128,
    /// Denominator of the canonical rational representative.
    pub denom: i128,
    /// Number of elements carrying this value.
    pub count: u128,
}

/// One p-primary summand of the finite-quadratic-module Witt class.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FqmPrimaryWittClass {
    /// The prime `p`.
    pub prime: u128,
    /// The order of the original p-primary summand.
    pub order: u128,
    /// The order of the anisotropic Witt core.
    pub core_order: u128,
    /// Invariant factors of the anisotropic core.
    pub core_group: Vec<u128>,
    /// Exponent of the anisotropic core.
    pub core_exponent: u128,
    /// The Milgram/Brown phase of this p-primary Witt class.
    pub phase_mod8: i128,
    /// Value counts on the anisotropic core, useful as readable diagnostics.
    pub q_value_counts: Vec<FqmValueCount>,
    /// Opaque exact normal form of the anisotropic core.
    ///
    /// The label is canonical under finite-module isomorphism; equality of these
    /// labels is the equality test for the p-primary Witt class.
    pub normal_form: Vec<i128>,
}

/// The Witt class of a nonsingular finite quadratic module.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FqmWittClass {
    /// Order of the original finite module.
    pub order: u128,
    /// Total Milgram/Brown phase, i.e. the sum of the p-primary phases in `Z/8`.
    pub phase_mod8: i128,
    /// Prime-local Witt normal forms.
    pub primary: Vec<FqmPrimaryWittClass>,
}

impl FqmWittClass {
    /// Whether the class is Witt-trivial, i.e. every p-primary anisotropic core is
    /// the zero module.
    pub fn is_trivial(&self) -> bool {
        self.primary.iter().all(|p| p.core_order == 1)
    }
}

/// A native finite quadratic module in a cyclic product presentation.
///
/// The `q_values_mod2` slice is ordered lexicographically over the cyclic factors:
/// for factors `[d0, d1, ...]`, index `((x0*d1 + x1)*d2 + ...)` stores
/// `q(x0, x1, ...)` as a rational in `Q/2Z`. The constructor validates
/// nonsingularity and the quadratic law up to `FQM_WITT_GROUP_CAP`.
#[derive(Clone, Debug, PartialEq)]
pub struct FiniteQuadraticModule {
    cyclic_factors: Vec<u128>,
    q_values_mod2: Vec<Rational>,
}

impl FiniteQuadraticModule {
    /// Build a nonsingular finite quadratic module from a cyclic presentation and
    /// all of its quadratic values in lexicographic coordinate order.
    pub fn new(cyclic_factors: Vec<u128>, q_values_mod2: Vec<Rational>) -> Option<Self> {
        if cyclic_factors.iter().any(|&d| d <= 1) {
            return None;
        }
        let order = cyclic_factors
            .iter()
            .try_fold(1usize, |acc, &d| acc.checked_mul(usize::try_from(d).ok()?))?;
        if order == 0 || order > FQM_WITT_GROUP_CAP || q_values_mod2.len() != order {
            return None;
        }
        let q_values_mod2 = q_values_mod2
            .into_iter()
            .map(|q| rational_mod_int(q, 2))
            .collect::<Vec<_>>();
        let module = FiniteQuadraticModule {
            cyclic_factors,
            q_values_mod2,
        };
        let table = FqmTable::from_native(&module)?;
        if table.q[table.zero] != Rational::zero()
            || !table.quadratic_values_are_even()
            || !table.bilinear_form_is_biadditive()
            || !table.is_nondegenerate()
        {
            return None;
        }
        Some(module)
    }

    /// The cyclic module generated by `g` with `q(g) = generator_q`.
    pub fn cyclic(order: u128, generator_q: Rational) -> Option<Self> {
        if order <= 1 || usize::try_from(order).ok()? > FQM_WITT_GROUP_CAP {
            return None;
        }
        let qg = rational_mod_int(generator_q, 2);
        let mut q_values = Vec::with_capacity(usize::try_from(order).ok()?);
        for k in 0..order {
            let kk = i128::try_from(k.checked_mul(k)?).ok()?;
            q_values.push(rational_mod_int(Rational::int(kk).mul(&qg), 2));
        }
        Self::new(vec![order], q_values)
    }

    /// Orthogonal direct sum.
    pub fn direct_sum(&self, other: &Self) -> Option<Self> {
        let left = FqmTable::from_native(self)?;
        let right = FqmTable::from_native(other)?;
        let mut factors = self.cyclic_factors.clone();
        factors.extend(other.cyclic_factors.iter().copied());
        let mut q_values = Vec::with_capacity(left.q.len().checked_mul(right.q.len())?);
        for ql in &left.q {
            for qr in &right.q {
                q_values.push(rational_mod_int(ql.add(qr), 2));
            }
        }
        Self::new(factors, q_values)
    }

    /// Order of the finite module.
    pub fn order(&self) -> u128 {
        self.q_values_mod2.len() as u128
    }

    /// Cyclic factors of this presentation.
    pub fn cyclic_factors(&self) -> &[u128] {
        &self.cyclic_factors
    }

    /// Quadratic values in lexicographic coordinate order.
    pub fn q_values_mod2(&self) -> &[Rational] {
        &self.q_values_mod2
    }

    /// The Wall/Nikulin Witt normal form.
    pub fn witt_class(&self) -> Option<FqmWittClass> {
        FqmTable::from_native(self)?.witt_class()
    }
}

impl DiscriminantForm {
    /// The full Wall/Nikulin finite-quadratic-module Witt class of `(A_L, q_L)`.
    ///
    /// This refines [`fqm_gauss_phase`](Self::fqm_gauss_phase): the phase is kept as
    /// a projection, but equality is decided by the p-primary anisotropic normal
    /// forms. The implementation is exact up to the finite enumeration budget; it
    /// returns `None` instead of truncating when `|A_L| > 512`.
    pub fn fqm_witt_class(&self) -> Option<FqmWittClass> {
        FqmTable::from_iso_tables(self.tables_bounded(FQM_WITT_GROUP_CAP)?).witt_class()
    }

    /// Whether two discriminant forms are Witt-equivalent as finite quadratic
    /// modules.
    pub fn is_fqm_witt_equivalent(&self, other: &Self) -> Option<bool> {
        Some(self.fqm_witt_class()? == other.fqm_witt_class()?)
    }
}

#[derive(Clone, Debug)]
struct FqmTable {
    zero: usize,
    q: Vec<Rational>,
    order: Vec<usize>,
    add: Vec<Vec<usize>>,
}

impl FqmTable {
    fn from_iso_tables(t: IsoTables) -> Self {
        FqmTable {
            zero: t.zero,
            q: t.q,
            order: t.order,
            add: t.add,
        }
    }

    fn from_native(module: &FiniteQuadraticModule) -> Option<Self> {
        let n = module.q_values_mod2.len();
        let mut add = vec![vec![0usize; n]; n];
        for i in 0..n {
            let ci = coords_from_index(i, &module.cyclic_factors)?;
            for j in 0..n {
                let cj = coords_from_index(j, &module.cyclic_factors)?;
                let sum = ci
                    .iter()
                    .zip(&cj)
                    .zip(&module.cyclic_factors)
                    .map(|((&a, &b), &d)| (a + b) % d)
                    .collect::<Vec<_>>();
                add[i][j] = index_from_coords(&sum, &module.cyclic_factors)?;
            }
        }
        let zero = 0;
        let mut out = FqmTable {
            zero,
            q: module.q_values_mod2.clone(),
            order: vec![1; n],
            add,
        };
        out.compute_orders();
        Some(out)
    }

    fn compute_orders(&mut self) {
        let n = self.q.len();
        self.order = vec![1usize; n];
        for i in 0..n {
            let mut cur = i;
            let mut k = 1usize;
            while cur != self.zero {
                cur = self.add[cur][i];
                k += 1;
            }
            self.order[i] = k;
        }
    }

    fn witt_class(&self) -> Option<FqmWittClass> {
        if self.q.len() > FQM_WITT_GROUP_CAP {
            return None;
        }
        let mut primes = BTreeSet::new();
        for &ord in &self.order {
            for p in prime_factors_u128(ord as u128) {
                primes.insert(p);
            }
        }
        let mut primary = Vec::new();
        for p in primes {
            let part = self.primary_subtable(p)?;
            let phase = phase_mod8_from_q_values(part.q.iter(), part.q.len())?;
            let mut memo = BTreeMap::new();
            let core = part.anisotropic_core(&mut memo)?;
            let core_phase = phase_mod8_from_q_values(core.q.iter(), core.q.len())?;
            if core_phase != phase {
                return None;
            }
            primary.push(FqmPrimaryWittClass {
                prime: p,
                order: part.q.len() as u128,
                core_order: core.q.len() as u128,
                core_group: core.primary_invariant_factors(p)?,
                core_exponent: core.order.iter().copied().max().unwrap_or(1) as u128,
                phase_mod8: phase,
                q_value_counts: core.q_value_counts(),
                normal_form: core.canonical_label()?,
            });
        }
        let phase_mod8 = primary
            .iter()
            .map(|p| p.phase_mod8)
            .sum::<i128>()
            .rem_euclid(8);
        Some(FqmWittClass {
            order: self.q.len() as u128,
            phase_mod8,
            primary,
        })
    }

    fn primary_subtable(&self, p: u128) -> Option<Self> {
        let indices = self
            .order
            .iter()
            .enumerate()
            .filter_map(|(i, &ord)| is_prime_power_order(ord as u128, p).then_some(i))
            .collect::<Vec<_>>();
        self.induced_subtable(&indices)
    }

    fn induced_subtable(&self, indices: &[usize]) -> Option<Self> {
        let mut map = vec![usize::MAX; self.q.len()];
        for (new, &old) in indices.iter().enumerate() {
            map[old] = new;
        }
        let zero = map[self.zero];
        if zero == usize::MAX {
            return None;
        }
        let mut add = vec![vec![0usize; indices.len()]; indices.len()];
        for (i, &old_i) in indices.iter().enumerate() {
            for (j, &old_j) in indices.iter().enumerate() {
                let s = self.add[old_i][old_j];
                let mapped = map[s];
                if mapped == usize::MAX {
                    return None;
                }
                add[i][j] = mapped;
            }
        }
        let mut out = FqmTable {
            zero,
            q: indices.iter().map(|&i| self.q[i].clone()).collect(),
            order: vec![1; indices.len()],
            add,
        };
        out.compute_orders();
        Some(out)
    }

    fn anisotropic_core(&self, memo: &mut BTreeMap<Vec<i128>, FqmTable>) -> Option<Self> {
        let raw = self.raw_label()?;
        if let Some(hit) = memo.get(&raw) {
            return Some(hit.clone());
        }
        let isotropic = (0..self.q.len())
            .filter(|&i| i != self.zero && self.q[i] == Rational::zero())
            .collect::<Vec<_>>();
        if isotropic.is_empty() {
            memo.insert(raw, self.clone());
            return Some(self.clone());
        }

        let mut best: Option<(Vec<i128>, FqmTable)> = None;
        for x in isotropic {
            let h = self.subgroup_generated(&[x]);
            if h.len() <= 1 {
                continue;
            }
            let quotient = self.quotient_by_isotropic_subgroup(&h)?;
            if quotient.q.len() >= self.q.len() {
                return None;
            }
            let core = quotient.anisotropic_core(memo)?;
            let label = core.canonical_label()?;
            if best.as_ref().is_none_or(|(b, _)| label < *b) {
                best = Some((label, core));
            }
        }
        let core = best?.1;
        memo.insert(raw, core.clone());
        Some(core)
    }

    fn quotient_by_isotropic_subgroup(&self, subgroup: &BTreeSet<usize>) -> Option<Self> {
        if !subgroup.contains(&self.zero)
            || !subgroup.iter().all(|&h| self.q[h] == Rational::zero())
        {
            return None;
        }
        let orthogonal = (0..self.q.len())
            .filter(|&x| {
                subgroup
                    .iter()
                    .all(|&h| self.bilinear_value(x, h) == Rational::zero())
            })
            .collect::<BTreeSet<_>>();
        if !subgroup.is_subset(&orthogonal) {
            return None;
        }

        let mut coset_of = vec![usize::MAX; self.q.len()];
        let mut reps = Vec::new();
        for &x in &orthogonal {
            if coset_of[x] != usize::MAX {
                continue;
            }
            let id = reps.len();
            reps.push(x);
            for &h in subgroup {
                let y = self.add[x][h];
                if !orthogonal.contains(&y) {
                    return None;
                }
                coset_of[y] = id;
            }
        }
        let zero = coset_of[self.zero];
        if zero == usize::MAX {
            return None;
        }
        let mut add = vec![vec![0usize; reps.len()]; reps.len()];
        for (i, &x) in reps.iter().enumerate() {
            for (j, &y) in reps.iter().enumerate() {
                let s = self.add[x][y];
                let mapped = coset_of[s];
                if mapped == usize::MAX {
                    return None;
                }
                add[i][j] = mapped;
            }
        }
        let mut out = FqmTable {
            zero,
            q: reps.iter().map(|&i| self.q[i].clone()).collect(),
            order: vec![1; reps.len()],
            add,
        };
        out.compute_orders();
        Some(out)
    }

    fn subgroup_generated(&self, gens: &[usize]) -> BTreeSet<usize> {
        let mut set = BTreeSet::new();
        let mut queue = VecDeque::new();
        set.insert(self.zero);
        queue.push_back(self.zero);
        while let Some(x) = queue.pop_front() {
            for &g in gens {
                let nx = self.add[x][g];
                if set.insert(nx) {
                    queue.push_back(nx);
                }
            }
        }
        set
    }

    fn generator_rank(&self) -> usize {
        let mut gens = Vec::new();
        let mut covered = self.subgroup_generated(&gens);
        while covered.len() < self.q.len() {
            let g = (0..self.q.len())
                .filter(|i| !covered.contains(i))
                .max_by_key(|&i| self.order[i])
                .expect("uncovered finite-module element exists");
            gens.push(g);
            covered = self.subgroup_generated(&gens);
        }
        gens.len()
    }

    fn canonical_label(&self) -> Option<Vec<i128>> {
        if self.q.len() == 1 {
            return Some(vec![1, 0]);
        }
        let rank = self.generator_rank();
        let candidates = (0..self.q.len())
            .filter(|&i| i != self.zero)
            .collect::<Vec<_>>();
        let mut tuple = Vec::with_capacity(rank);
        let mut best: Option<Vec<i128>> = None;
        let mut seen = 0u128;
        self.canonical_label_rec(rank, &candidates, &mut tuple, &mut best, &mut seen)?;
        best
    }

    fn canonical_label_rec(
        &self,
        rank: usize,
        candidates: &[usize],
        tuple: &mut Vec<usize>,
        best: &mut Option<Vec<i128>>,
        seen: &mut u128,
    ) -> Option<()> {
        if tuple.len() == rank {
            *seen = seen.checked_add(1)?;
            if *seen > FQM_WITT_TUPLE_CAP {
                return None;
            }
            if let Some(order) = self.ordered_elements_from_generators(tuple) {
                let label = self.label_for_order(&order)?;
                if best.as_ref().is_none_or(|b| label < *b) {
                    *best = Some(label);
                }
            }
            return Some(());
        }
        for &cand in candidates {
            if tuple.contains(&cand) {
                continue;
            }
            tuple.push(cand);
            self.canonical_label_rec(rank, candidates, tuple, best, seen)?;
            tuple.pop();
        }
        Some(())
    }

    fn ordered_elements_from_generators(&self, gens: &[usize]) -> Option<Vec<usize>> {
        let mut order = vec![self.zero];
        let mut seen = vec![false; self.q.len()];
        seen[self.zero] = true;
        let mut cursor = 0usize;
        while cursor < order.len() {
            let x = order[cursor];
            for &g in gens {
                let nx = self.add[x][g];
                if !seen[nx] {
                    seen[nx] = true;
                    order.push(nx);
                }
            }
            cursor += 1;
        }
        (order.len() == self.q.len()).then_some(order)
    }

    fn label_for_order(&self, order: &[usize]) -> Option<Vec<i128>> {
        let mut pos = vec![usize::MAX; self.q.len()];
        for (i, &old) in order.iter().enumerate() {
            pos[old] = i;
        }
        let mut out = Vec::with_capacity(2 + 2 * order.len() + order.len() * order.len());
        out.push(i128::try_from(order.len()).ok()?);
        for &old in order {
            out.push(self.q[old].numer());
            out.push(self.q[old].denom());
        }
        for &x in order {
            for &y in order {
                out.push(i128::try_from(pos[self.add[x][y]]).ok()?);
            }
        }
        Some(out)
    }

    fn raw_label(&self) -> Option<Vec<i128>> {
        let order = (0..self.q.len()).collect::<Vec<_>>();
        self.label_for_order(&order)
    }

    fn q_value_counts(&self) -> Vec<FqmValueCount> {
        let mut counts: BTreeMap<(i128, i128), u128> = BTreeMap::new();
        for q in &self.q {
            *counts.entry((q.numer(), q.denom())).or_default() += 1;
        }
        counts
            .into_iter()
            .map(|((numer, denom), count)| FqmValueCount {
                numer,
                denom,
                count,
            })
            .collect()
    }

    fn primary_invariant_factors(&self, p: u128) -> Option<Vec<u128>> {
        let exponent = self.order.iter().copied().max().unwrap_or(1) as u128;
        let max_power = exact_prime_power_exponent(exponent, p)?;
        let mut killed_log = vec![0u128; usize::try_from(max_power + 1).ok()?];
        killed_log[0] = 0;
        let mut p_to_j = 1u128;
        for j in 1..=max_power {
            p_to_j = p_to_j.checked_mul(p)?;
            let count = self
                .order
                .iter()
                .filter(|&&ord| p_to_j.is_multiple_of(ord as u128))
                .count() as u128;
            killed_log[usize::try_from(j).ok()?] = exact_prime_power_exponent(count, p)?;
        }

        let mut ge = vec![0u128; usize::try_from(max_power + 2).ok()?];
        for j in 1..=max_power {
            let ji = usize::try_from(j).ok()?;
            ge[ji] = killed_log[ji].checked_sub(killed_log[ji - 1])?;
        }
        let mut factors = Vec::new();
        for j in 1..=max_power {
            let ji = usize::try_from(j).ok()?;
            let exact = ge[ji].checked_sub(ge[ji + 1])?;
            let factor = pow_u128(p, j)?;
            for _ in 0..exact {
                factors.push(factor);
            }
        }
        Some(factors)
    }

    fn bilinear_value(&self, x: usize, y: usize) -> Rational {
        let diff = self.q[self.add[x][y]].sub(&self.q[x]).sub(&self.q[y]);
        rational_half_mod1(diff)
    }

    fn quadratic_values_are_even(&self) -> bool {
        (0..self.q.len()).all(|x| {
            let nx = self.neg(x);
            self.q[nx] == self.q[x]
        })
    }

    fn bilinear_form_is_biadditive(&self) -> bool {
        for x in 0..self.q.len() {
            for y in 0..self.q.len() {
                for z in 0..self.q.len() {
                    let yz = self.add[y][z];
                    let lhs = self.bilinear_value(x, yz);
                    let rhs = rational_mod_int(
                        self.bilinear_value(x, y).add(&self.bilinear_value(x, z)),
                        1,
                    );
                    if lhs != rhs {
                        return false;
                    }
                    let xy = self.add[x][y];
                    let lhs = self.bilinear_value(xy, z);
                    let rhs = rational_mod_int(
                        self.bilinear_value(x, z).add(&self.bilinear_value(y, z)),
                        1,
                    );
                    if lhs != rhs {
                        return false;
                    }
                }
            }
        }
        true
    }

    fn is_nondegenerate(&self) -> bool {
        (0..self.q.len()).all(|x| {
            x == self.zero
                || (0..self.q.len()).any(|y| self.bilinear_value(x, y) != Rational::zero())
        })
    }

    fn neg(&self, x: usize) -> usize {
        (0..self.q.len())
            .find(|&y| self.add[x][y] == self.zero)
            .expect("finite abelian group element has an inverse")
    }
}

fn coords_from_index(mut index: usize, factors: &[u128]) -> Option<Vec<u128>> {
    let mut out = vec![0u128; factors.len()];
    for (i, &d) in factors.iter().enumerate().rev() {
        let du = usize::try_from(d).ok()?;
        out[i] = (index % du) as u128;
        index /= du;
    }
    Some(out)
}

fn index_from_coords(coords: &[u128], factors: &[u128]) -> Option<usize> {
    let mut out = 0usize;
    for (&x, &d) in coords.iter().zip(factors) {
        if x >= d {
            return None;
        }
        out = out
            .checked_mul(usize::try_from(d).ok()?)?
            .checked_add(usize::try_from(x).ok()?)?;
    }
    Some(out)
}

fn rational_mod_int(x: Rational, modulus: i128) -> Rational {
    debug_assert!(modulus > 0);
    let den = x.denom();
    let mden = den
        .checked_mul(modulus)
        .expect("rational modulus exceeds i128");
    Rational::new(x.numer().rem_euclid(mden), den)
}

fn rational_half_mod1(x: Rational) -> Rational {
    let den = x
        .denom()
        .checked_mul(2)
        .expect("rational denominator exceeds i128");
    rational_mod_int(Rational::new(x.numer(), den), 1)
}

fn prime_factors_u128(n: u128) -> Vec<u128> {
    let mut m = n;
    let mut out = Vec::new();
    let mut p = 2u128;
    while p <= m / p {
        if m.is_multiple_of(p) {
            out.push(p);
            while m.is_multiple_of(p) {
                m /= p;
            }
        }
        p += if p == 2 { 1 } else { 2 };
    }
    if m > 1 {
        out.push(m);
    }
    out
}

fn is_prime_power_order(order: u128, p: u128) -> bool {
    if order == 1 {
        return true;
    }
    let mut m = order;
    while m.is_multiple_of(p) {
        m /= p;
    }
    m == 1
}

fn exact_prime_power_exponent(mut n: u128, p: u128) -> Option<u128> {
    if n == 1 {
        return Some(0);
    }
    let mut k = 0u128;
    while n > 1 && n.is_multiple_of(p) {
        n /= p;
        k += 1;
    }
    (n == 1).then_some(k)
}

fn pow_u128(base: u128, exp: u128) -> Option<u128> {
    let mut out = 1u128;
    for _ in 0..exp {
        out = out.checked_mul(base)?;
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::forms::{a_n, e_6, e_7, DiscriminantForm};

    #[test]
    fn native_cyclic_module_matches_lattice_a1() {
        let native = FiniteQuadraticModule::cyclic(2, Rational::new(1, 2)).unwrap();
        let from_lattice = DiscriminantForm::from_lattice(&a_n(1))
            .unwrap()
            .fqm_witt_class()
            .unwrap();
        assert_eq!(native.witt_class().unwrap(), from_lattice);
    }

    #[test]
    fn fqm_witt_reduces_hyperbolic_two_primary_pair() {
        let a1 = DiscriminantForm::from_lattice(&a_n(1)).unwrap();
        let e7 = DiscriminantForm::from_lattice(&e_7()).unwrap();
        assert_ne!(a1.fqm_witt_class().unwrap(), e7.fqm_witt_class().unwrap());

        let hyperbolic = FiniteQuadraticModule::cyclic(2, Rational::new(1, 2))
            .unwrap()
            .direct_sum(&FiniteQuadraticModule::cyclic(2, Rational::new(3, 2)).unwrap())
            .unwrap();
        let class = hyperbolic.witt_class().unwrap();
        assert!(class.is_trivial());
        assert_eq!(class.phase_mod8, 0);
    }

    #[test]
    fn fqm_witt_reduces_hyperbolic_odd_primary_pair() {
        let a2 = DiscriminantForm::from_lattice(&a_n(2)).unwrap();
        let e6 = DiscriminantForm::from_lattice(&e_6()).unwrap();
        assert_eq!(a2.is_fqm_witt_equivalent(&e6), Some(false));
        assert!(DiscriminantForm::from_lattice(&a_n(2).direct_sum(&e_6()))
            .unwrap()
            .fqm_witt_class()
            .unwrap()
            .is_trivial());

        let sum = FiniteQuadraticModule::cyclic(3, Rational::new(2, 3))
            .unwrap()
            .direct_sum(&FiniteQuadraticModule::cyclic(3, Rational::new(4, 3)).unwrap())
            .unwrap();
        let class = sum.witt_class().unwrap();
        assert!(class.is_trivial());
        assert_eq!(class.phase_mod8, 0);
    }

    #[test]
    fn fqm_witt_refines_phase_projection() {
        let a1 = DiscriminantForm::from_lattice(&a_n(1)).unwrap();
        let class = a1.fqm_witt_class().unwrap();
        let phase = a1.fqm_gauss_phase().unwrap();
        assert_eq!(class.order, phase.order as u128);
        assert_eq!(class.phase_mod8, phase.phase_mod8);
        assert_eq!(class.primary[0].phase_mod8, phase.primary[0].phase_mod8);
        assert_eq!(class.primary[0].core_group, vec![2]);
        assert_eq!(class.primary[0].q_value_counts.len(), 2);
    }
}
