//! The Brauer–Wall group `BW(F)` — the abstract home all three Clifford
//! classifiers are shadows of.
//!
//! `BW(F)` is the group of **graded** central simple algebras over `F` up to graded
//! Morita equivalence, under the **graded tensor product** `⊗̂`. The Clifford
//! algebra of a quadratic form is graded-central-simple, and `Q ↦ [Cl(Q)]` sends
//! the orthogonal sum `⊥` to `⊗̂` (precisely [`CliffordAlgebra::graded_tensor`],
//! built on [`Metric::direct_sum`]) and sends hyperbolic planes to `0` (`Cl(H) =
//! M₂(F)` is graded-trivial). So the class factors through the Witt group, and the
//! three classifier legs of this crate are the three computations of `BW(F)`:
//!
//!   * **`BW(ℝ) ≅ ℤ/8`** — and this `ℤ/8` *is* the Bott clock `forms/char0.rs`
//!     already tabulates: the class of `Cl(p,q)` is the index `s = (q − p) mod 8`,
//!     and `⊗̂` adds it mod 8. The 8-fold periodicity table and `BW(ℝ)` are the same
//!     object; here it becomes a *group*.
//!   * **`BW(ℂ) ≅ ℤ/2`** — the class is the dimension parity `n mod 2`.
//!   * **`BW(F_q)`** — finite fields have trivial Brauer group, so `BW(F_q)` is the
//!     order-4 graded part, *isomorphic to* `W(F_q)`: `ℤ/4` when `−1` is a nonsquare
//!     (`q ≡ 3 mod 4`) and `ℤ/2 × ℤ/2` when it is a square (`q ≡ 1 mod 4`). We do
//!     **not** assert this — the tests *discover* the order and the dichotomy by
//!     walking the subgroup generated by `[Cl⟨a⟩]` under `⊗̂`, reusing the verified
//!     `oddchar` data as the class.
//!
//! The unifier in code: `[Cl(V) ⊗̂ Cl(W)] = [Cl(V)] + [Cl(W)]` is checked against
//! the *actual* `direct_sum`/`graded_tensor`, in every leg.

use crate::clifford::Metric;
use crate::forms::{
    classify_surcomplex, classify_surreal, finite_odd_witt, FiniteOddField, WittClassG,
};
use crate::scalar::{Surcomplex, Surreal};

/// A class in the Brauer–Wall group, by characteristic leg. Each leg's `add` is the
/// group law induced by the graded tensor product `⊗̂`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BrauerWallClass {
    /// `BW(ℝ) ≅ ℤ/8`: the Bott index `s = (q − p) mod 8`.
    Real(u8),
    /// `BW(ℂ) ≅ ℤ/2`: the dimension parity.
    Complex(u8),
    /// `BW(F_q)`: the order-4 graded part, carried as the `oddchar` Witt data.
    OddChar { kappa: u8, e0: u8, sclass: u8 },
}

impl BrauerWallClass {
    /// The group operation induced by the graded tensor product `⊗̂`. Panics across
    /// different legs (you cannot tensor algebras over different ground fields).
    pub fn add(&self, other: &BrauerWallClass) -> BrauerWallClass {
        match (*self, *other) {
            (BrauerWallClass::Real(a), BrauerWallClass::Real(b)) => {
                BrauerWallClass::Real((a + b) % 8)
            }
            (BrauerWallClass::Complex(a), BrauerWallClass::Complex(b)) => {
                BrauerWallClass::Complex((a + b) % 2)
            }
            (
                BrauerWallClass::OddChar {
                    kappa: ka,
                    e0: e0a,
                    sclass: sa,
                },
                BrauerWallClass::OddChar {
                    kappa: kb,
                    e0: e0b,
                    sclass: sb,
                },
            ) => {
                // The BW(F_q) law is exactly the order-4 odd-char Witt group law.
                let w = WittClassG::OddChar {
                    kappa: ka,
                    e0: e0a,
                    sclass: sa,
                }
                .add(&WittClassG::OddChar {
                    kappa: kb,
                    e0: e0b,
                    sclass: sb,
                });
                match w {
                    WittClassG::OddChar { kappa, e0, sclass } => {
                        BrauerWallClass::OddChar { kappa, e0, sclass }
                    }
                    _ => unreachable!(),
                }
            }
            _ => panic!("cannot add Brauer–Wall classes across different ground fields"),
        }
    }

    /// The identity (graded-trivial class) of the leg this class lives in.
    pub fn zero_like(&self) -> BrauerWallClass {
        match *self {
            BrauerWallClass::Real(_) => BrauerWallClass::Real(0),
            BrauerWallClass::Complex(_) => BrauerWallClass::Complex(0),
            BrauerWallClass::OddChar { kappa, .. } => BrauerWallClass::OddChar {
                kappa,
                e0: 0,
                sclass: 0,
            },
        }
    }
}

/// The Brauer–Wall class of `Cl(Q)` over the **reals** (surreal backend):
/// `s = (q − p) mod 8`, the Bott index. Reuses [`classify_surreal`]'s signature
/// reading — so this `ℤ/8` *is literally* the char-0 periodicity table. `None` if
/// the metric is non-diagonal.
pub fn bw_class_real(metric: &Metric<Surreal>) -> Option<BrauerWallClass> {
    let (p, q) = classify_surreal(metric)?.signature;
    Some(BrauerWallClass::Real(
        (q as isize - p as isize).rem_euclid(8) as u8,
    ))
}

/// The Brauer–Wall class of `Cl(Q)` over the **complexes** (surcomplex backend):
/// the dimension parity `n mod 2`. `None` if non-diagonal.
pub fn bw_class_complex(metric: &Metric<Surcomplex<Surreal>>) -> Option<BrauerWallClass> {
    let ct = classify_surcomplex(metric)?;
    let (p, q) = ct.signature;
    Some(BrauerWallClass::Complex(((p + q) % 2) as u8))
}

/// The Brauer–Wall class of `Cl(Q)` over any finite field `F_q` of odd
/// characteristic, carried as the order-4 `oddchar` Witt data (`BW(F_q) ≅ W(F_q)`
/// over a finite field, since the Brauer group is trivial). `None` if non-diagonal.
pub fn bw_class_finite_odd<F: FiniteOddField>(metric: &Metric<F>) -> Option<BrauerWallClass> {
    match finite_odd_witt(metric)? {
        WittClassG::OddChar { kappa, e0, sclass } => {
            Some(BrauerWallClass::OddChar { kappa, e0, sclass })
        }
        _ => unreachable!("finite_odd_witt returns the OddChar variant"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::clifford::CliffordAlgebra;
    use crate::forms::classify_real;
    use crate::scalar::{Fp, Scalar, Surcomplex};
    use std::collections::BTreeSet;

    fn real_diag(signs: &[i32]) -> Metric<Surreal> {
        Metric::diagonal(
            signs
                .iter()
                .map(|&s| {
                    if s >= 0 {
                        Surreal::one()
                    } else {
                        Surreal::one().neg()
                    }
                })
                .collect(),
        )
    }

    /// The order of the cyclic subgroup generated by `g` under `add` (walk to identity).
    fn subgroup_order(g: BrauerWallClass) -> usize {
        let id = g.zero_like();
        let mut cur = g;
        let mut n = 1;
        while cur != id {
            cur = cur.add(&g);
            n += 1;
            assert!(n <= 64, "subgroup walk did not close — bug in add");
        }
        n
    }

    #[test]
    fn bw_real_is_the_bott_clock() {
        // The unifier: bw_class_real of Cl(p,q) is exactly classify_real's index
        // s = (q − p) mod 8 — BW(ℝ) and the 8-fold periodicity table coincide.
        for p in 0..5usize {
            for q in 0..5usize {
                let signs: Vec<i32> = std::iter::repeat(1)
                    .take(p)
                    .chain(std::iter::repeat(-1).take(q))
                    .collect();
                if signs.is_empty() {
                    continue;
                }
                let s = (q as isize - p as isize).rem_euclid(8) as u8;
                assert_eq!(
                    bw_class_real(&real_diag(&signs)),
                    Some(BrauerWallClass::Real(s))
                );
                // and classify_real agrees this is the indexing it uses
                let _ = classify_real(p, q, 0); // (its `base`/`matrix_dim` derive from s)
            }
        }
    }

    #[test]
    fn bw_real_is_homomorphism_over_graded_tensor() {
        // [Cl(V) ⊗̂ Cl(W)] = [Cl(V)] + [Cl(W)], checked against the ACTUAL
        // graded_tensor / direct_sum, not just the abstract law.
        let v = real_diag(&[1, 1, -1]); // (p,q) = (2,1)
        let w = real_diag(&[-1, -1]); //  (p,q) = (0,2)
        let av = CliffordAlgebra::new(3, v.clone());
        let aw = CliffordAlgebra::new(2, w.clone());
        let tensored = av.graded_tensor(&aw);
        assert_eq!(
            bw_class_real(&tensored.metric),
            Some(bw_class_real(&v).unwrap().add(&bw_class_real(&w).unwrap()))
        );
    }

    #[test]
    fn bw_real_discovers_z8() {
        // Walk the subgroup generated by [Cl⟨−1⟩] (s = 1): it is cyclic of order 8.
        // DISCOVERS BW(ℝ) ≅ ℤ/8 rather than asserting it.
        let g = bw_class_real(&real_diag(&[-1])).unwrap();
        assert_eq!(g, BrauerWallClass::Real(1));
        assert_eq!(subgroup_order(g), 8);
        // [Cl⟨1⟩] has s = 7, also a generator (gcd(7,8)=1).
        let h = bw_class_real(&real_diag(&[1])).unwrap();
        assert_eq!(h, BrauerWallClass::Real(7));
        assert_eq!(subgroup_order(h), 8);
    }

    #[test]
    fn bw_complex_is_z2() {
        let one = Surcomplex::<Surreal>::one();
        let m1 = Metric::diagonal(vec![one.clone()]);
        let m2 = Metric::diagonal(vec![one.clone(), one.clone()]);
        assert_eq!(bw_class_complex(&m1), Some(BrauerWallClass::Complex(1)));
        assert_eq!(bw_class_complex(&m2), Some(BrauerWallClass::Complex(0)));
        assert_eq!(subgroup_order(BrauerWallClass::Complex(1)), 2);
    }

    fn oddchar_diag<const P: u128>(qs: &[u128]) -> Metric<Fp<P>> {
        Metric::diagonal(qs.iter().map(|&x| Fp::<P>(x)).collect())
    }

    #[test]
    fn bw_oddchar_homomorphism_and_discovered_order_four() {
        // The class is a homomorphism over direct_sum (= graded tensor of Cliffords),
        // and the group it generates has order 4 — discovered, with the q mod 4
        // dichotomy: ℤ/4 over F_3 (−1 nonsquare), (ℤ/2)² over F_5 (−1 square).
        fn collect_group<const P: u128>() -> (BTreeSet<(u8, u8, u8)>, bool) {
            // generate from ⟨1⟩ and ⟨nonsquare⟩, closing under add
            let gens: Vec<BrauerWallClass> = (1..P)
                .map(|a| bw_class_finite_odd(&oddchar_diag::<P>(&[a])).unwrap())
                .collect();
            let mut seen: BTreeSet<(u8, u8, u8)> = BTreeSet::new();
            let key = |c: &BrauerWallClass| match *c {
                BrauerWallClass::OddChar { kappa, e0, sclass } => (kappa, e0, sclass),
                _ => unreachable!(),
            };
            let id = gens[0].zero_like();
            let mut frontier = vec![id];
            seen.insert(key(&id));
            while let Some(x) = frontier.pop() {
                for g in &gens {
                    let y = x.add(g);
                    if seen.insert(key(&y)) {
                        frontier.push(y);
                    }
                }
            }
            // is there an element of order 4 (⇒ cyclic ℤ/4)?
            let has_order_4 = gens.iter().any(|&g| subgroup_order(g) == 4);
            (seen, has_order_4)
        }

        // homomorphism check against actual direct_sum
        let a = oddchar_diag::<3>(&[1, 2]);
        let b = oddchar_diag::<3>(&[2]);
        assert_eq!(
            bw_class_finite_odd(&a.direct_sum(&b)),
            Some(
                bw_class_finite_odd(&a)
                    .unwrap()
                    .add(&bw_class_finite_odd(&b).unwrap())
            )
        );

        let (g3, cyclic3) = collect_group::<3>();
        assert_eq!(g3.len(), 4, "BW(F_3) discovered order");
        assert!(cyclic3, "BW(F_3) ≅ ℤ/4 (−1 nonsquare)");

        let (g5, cyclic5) = collect_group::<5>();
        assert_eq!(g5.len(), 4, "BW(F_5) discovered order");
        assert!(
            !cyclic5,
            "BW(F_5) ≅ (ℤ/2)² (−1 square): no element of order 4"
        );
    }
}
