//! The **exterior algebra of the game group**: `Λ` over `ℤ` on a chosen tuple of
//! games. This is the Clifford-adjacent structure that lives on *all* of
//! game-world — not just the field-like numbers — because the partizan games form
//! an abelian group (a `ℤ`-module), and the Grassmann algebra is the exterior
//! algebra of that module.
//!
//! [`GameExterior`] wraps the free Grassmann engine ([`CliffordAlgebra`] over
//! [`Integer`] with the all-zero metric) and quotients it by the integer
//! relations that actually hold among the chosen generators (e.g. `2⋆ = 0`), so a
//! relation propagates through the exterior ideal: `2⋆ = 0 ⟹ 2(⋆∧↑) = 0`. The
//! relations are either supplied explicitly or discovered by a small bounded
//! search; the integer-lattice reduction that imposes them is the row machinery
//! at the bottom of this file.
//!
//! Generators may be non-numbers (`⋆`, `↑`, switches) — exactly where the
//! Clifford/scalar story cannot go — which is the point: the [`Game`] group is not
//! a ring, but it *is* a `ℤ`-module, and that is enough for `Λ`.

use super::Game;
use crate::clifford::{bits, CliffordAlgebra, Metric, Multivector};
use crate::scalar::Integer;
use std::collections::{BTreeMap, BTreeSet};

const DEFAULT_RELATION_BOUND: i128 = 3;
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GameRelation {
    pub coeffs: Vec<i128>,
}

impl GameRelation {
    pub fn new(coeffs: Vec<i128>) -> Self {
        assert!(
            coeffs.iter().any(|&c| c != 0),
            "game relation must be nonzero"
        );
        GameRelation { coeffs }
    }
}

/// The exterior algebra generated by a chosen tuple of games, quotienting the
/// free Grassmann algebra by known integer relations among those games.
///
/// The raw [`algebra`](Self::algebra) is still the free Grassmann engine. The
/// quotient-aware operations ([`reduce`](Self::reduce), [`wedge`](Self::wedge),
/// [`add`](Self::add), [`is_zero`](Self::is_zero)) impose the exterior ideal
/// generated by the stored grade-1 relations, so a relation such as `2⋆ = 0`
/// propagates to `2(⋆∧↑) = 0`.
#[derive(Clone)]
pub struct GameExterior {
    alg: CliffordAlgebra<Integer>,
    gens: Vec<Game>,
    relations: Vec<GameRelation>,
}

impl GameExterior {
    pub fn new(gens: Vec<Game>) -> GameExterior {
        GameExterior::with_relation_search(gens, DEFAULT_RELATION_BOUND)
    }

    /// The free Grassmann algebra on the chosen generators, with no game-group
    /// relations imposed. Useful as the ambient object when explicit quotienting
    /// is not desired.
    pub fn free(gens: Vec<Game>) -> GameExterior {
        GameExterior::with_relations(gens, vec![])
    }

    /// Build the quotient using small discovered relations `Σ c_i g_i = 0`.
    /// Automatic discovery always checks singleton torsion and checks pair/full
    /// coefficient searches only for two-generator presentations; larger
    /// presentations should use [`with_relations`](Self::with_relations) for
    /// known cross-generator relations.
    pub fn with_relation_search(gens: Vec<Game>, bound: i128) -> GameExterior {
        let relations = discover_relations(&gens, bound);
        GameExterior::with_relations(gens, relations)
    }

    /// Build the quotient from explicit integer relations among the supplied
    /// generators. Each relation is verified against the game group before it is
    /// accepted.
    pub fn with_relations(gens: Vec<Game>, relations: Vec<GameRelation>) -> GameExterior {
        let n = gens.len();
        for rel in &relations {
            assert_eq!(
                rel.coeffs.len(),
                n,
                "game relation length must match generator count"
            );
            assert!(
                eval_relation(&gens, &rel.coeffs).eq(&Game::zero()),
                "declared game relation does not evaluate to zero"
            );
        }
        GameExterior {
            alg: CliffordAlgebra::new(n, Metric::grassmann(n)),
            gens,
            relations,
        }
    }

    /// The underlying free Grassmann algebra. Use the quotient-aware methods on
    /// `GameExterior` when game-group relations should be imposed.
    pub fn algebra(&self) -> &CliffordAlgebra<Integer> {
        &self.alg
    }

    pub fn relations(&self) -> &[GameRelation] {
        &self.relations
    }

    /// The grade-1 generator `e_i` (corresponding to the game `g_i`).
    pub fn generator(&self, i: usize) -> Multivector<Integer> {
        self.reduce(&self.alg.gen(i))
    }

    /// The game `g_i` a generator stands for.
    pub fn game(&self, i: usize) -> &Game {
        &self.gens[i]
    }

    /// The module map `Λ¹ → (game group)`: send a grade-1 element `Σ c_i e_i` to
    /// the game `Σ c_i · g_i`. Defined entirely with the game *group* operations
    /// (sum, negation, integer multiple) and no game product — so it is valid for
    /// non-number generators. Panics if `mv` is not purely grade 1.
    pub fn value_of_grade1(&self, mv: &Multivector<Integer>) -> Game {
        let mut acc = Game::zero();
        let mv = self.reduce(mv);
        for (&blade, coeff) in &mv.terms {
            assert_eq!(
                blade.count_ones(),
                1,
                "value_of_grade1 expects a grade-1 element"
            );
            let i = blade.trailing_zeros() as usize;
            acc = acc.add(&self.gens[i].times_int(coeff.0));
        }
        acc
    }

    pub fn add(&self, a: &Multivector<Integer>, b: &Multivector<Integer>) -> Multivector<Integer> {
        self.reduce(&self.alg.add(a, b))
    }

    pub fn scalar_mul(&self, s: i128, a: &Multivector<Integer>) -> Multivector<Integer> {
        self.reduce(&self.alg.scalar_mul(&Integer(s), a))
    }

    pub fn wedge(
        &self,
        a: &Multivector<Integer>,
        b: &Multivector<Integer>,
    ) -> Multivector<Integer> {
        self.reduce(&self.alg.wedge(a, b))
    }

    pub fn is_zero(&self, mv: &Multivector<Integer>) -> bool {
        self.reduce(mv).is_zero()
    }

    /// Reduce a free Grassmann multivector modulo the exterior ideal generated by
    /// the stored game relations.
    pub fn reduce(&self, mv: &Multivector<Integer>) -> Multivector<Integer> {
        if self.relations.is_empty() || mv.is_zero() {
            return mv.clone();
        }
        let mut out = self.alg.zero();
        let mut by_grade: BTreeMap<usize, BTreeMap<u128, i128>> = BTreeMap::new();
        for (&blade, coeff) in &mv.terms {
            by_grade
                .entry(blade.count_ones() as usize)
                .or_default()
                .insert(blade, coeff.0);
        }
        for (grade, terms) in by_grade {
            let reduced = self.reduce_grade(grade, &terms);
            for (blade, coeff) in reduced {
                if coeff != 0 {
                    out.terms.insert(blade, Integer(coeff));
                }
            }
        }
        out
    }

    fn reduce_grade(&self, grade: usize, terms: &BTreeMap<u128, i128>) -> BTreeMap<u128, i128> {
        if grade == 0 {
            return terms.clone();
        }
        let basis = grade_masks(self.gens.len(), grade);
        if basis.is_empty() {
            return BTreeMap::new();
        }
        let index: BTreeMap<u128, usize> = basis.iter().enumerate().map(|(i, &m)| (m, i)).collect();
        let mut v = vec![0i128; basis.len()];
        for (&blade, &coeff) in terms {
            if let Some(&i) = index.get(&blade) {
                v[i] += coeff;
            }
        }
        let rows = self.relation_rows_for_grade(grade, &basis, &index);
        reduce_integer_vector(&mut v, rows);
        basis.into_iter().zip(v).filter(|&(_, c)| c != 0).collect()
    }

    fn relation_rows_for_grade(
        &self,
        grade: usize,
        basis: &[u128],
        index: &BTreeMap<u128, usize>,
    ) -> Vec<Vec<i128>> {
        let mut rows = Vec::new();
        let lower_basis = grade_masks(self.gens.len(), grade - 1);
        for rel in &self.relations {
            let rel_mv = relation_multivector(rel);
            for mask in &lower_basis {
                let blade = self.alg.blade(&bits(*mask));
                let wedged = self.alg.wedge(&rel_mv, &blade);
                let mut row = vec![0i128; basis.len()];
                for (&b, coeff) in &wedged.terms {
                    if let Some(&i) = index.get(&b) {
                        row[i] += coeff.0;
                    }
                }
                if row.iter().any(|&x| x != 0) {
                    rows.push(row);
                }
            }
        }
        rows
    }
}

fn relation_multivector(rel: &GameRelation) -> Multivector<Integer> {
    let mut terms = BTreeMap::new();
    for (i, &coeff) in rel.coeffs.iter().enumerate() {
        if coeff != 0 {
            terms.insert(1u128 << i, Integer(coeff));
        }
    }
    Multivector { terms }
}

fn eval_relation(gens: &[Game], coeffs: &[i128]) -> Game {
    let mut acc = Game::zero();
    for (g, &c) in gens.iter().zip(coeffs) {
        acc = acc.add(&g.times_int(c));
    }
    acc
}

fn canonical_relation(mut coeffs: Vec<i128>) -> Option<Vec<i128>> {
    let first = coeffs.iter().position(|&c| c != 0)?;
    if coeffs[first] < 0 {
        for c in &mut coeffs {
            *c = -*c;
        }
    }
    Some(coeffs)
}

fn discover_relations(gens: &[Game], bound: i128) -> Vec<GameRelation> {
    if gens.is_empty() || bound <= 0 {
        return Vec::new();
    }
    let n = gens.len();
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();

    for i in 0..n {
        for c in 1..=bound {
            let mut coeffs = vec![0i128; n];
            coeffs[i] = c;
            if push_relation_if_independent(gens, coeffs, &mut seen, &mut out) {
                break;
            }
        }
    }

    if n > 2 {
        return out;
    }

    let mut candidates = Vec::new();
    for i in 0..n {
        for j in (i + 1)..n {
            for a in -bound..=bound {
                for b in -bound..=bound {
                    if a == 0 && b == 0 {
                        continue;
                    }
                    let mut coeffs = vec![0i128; n];
                    coeffs[i] = a;
                    coeffs[j] = b;
                    let Some(key) = canonical_relation(coeffs) else {
                        continue;
                    };
                    candidates.push(key);
                }
            }
        }
    }
    candidates.sort_by_key(|v| (v.iter().map(|c| c.abs()).sum::<i128>(), v.clone()));
    for coeffs in candidates {
        push_relation_if_independent(gens, coeffs, &mut seen, &mut out);
    }
    out
}

fn push_relation_if_independent(
    gens: &[Game],
    coeffs: Vec<i128>,
    seen: &mut BTreeSet<Vec<i128>>,
    out: &mut Vec<GameRelation>,
) -> bool {
    let Some(key) = canonical_relation(coeffs) else {
        return false;
    };
    if !seen.insert(key.clone()) {
        return false;
    }
    if !eval_relation(gens, &key).eq(&Game::zero()) {
        return false;
    }
    let mut reduced = key.clone();
    let rows: Vec<Vec<i128>> = out.iter().map(|r| r.coeffs.clone()).collect();
    reduce_integer_vector(&mut reduced, rows);
    if reduced.iter().all(|&c| c == 0) {
        return false;
    }
    out.push(GameRelation::new(key));
    true
}

fn grade_masks(n: usize, grade: usize) -> Vec<u128> {
    if grade > n {
        return Vec::new();
    }
    fn rec(n: usize, grade: usize, start: usize, mask: u128, out: &mut Vec<u128>) {
        if grade == 0 {
            out.push(mask);
            return;
        }
        for i in start..=n - grade {
            rec(n, grade - 1, i + 1, mask | (1u128 << i), out);
        }
    }
    let mut out = Vec::new();
    rec(n, grade, 0, 0, &mut out);
    out
}

fn leading(row: &[i128]) -> Option<usize> {
    row.iter().position(|&x| x != 0)
}

fn row_is_zero(row: &[i128]) -> bool {
    row.iter().all(|&x| x == 0)
}

fn checked_abs(x: i128) -> i128 {
    x.checked_abs()
        .expect("integer relation coefficient magnitude exceeds i128")
}

fn negate_row(row: &mut [i128]) {
    for x in row {
        *x = x
            .checked_neg()
            .expect("integer relation coefficient magnitude exceeds i128");
    }
}

fn sub_row_multiple(target: &mut [i128], source: &[i128], q: i128) {
    for (t, &s) in target.iter_mut().zip(source) {
        let delta = q
            .checked_mul(s)
            .expect("integer relation row operation exceeds i128");
        *t = t
            .checked_sub(delta)
            .expect("integer relation row operation exceeds i128");
    }
}

/// Row Hermite normal form for an integer row lattice.
///
/// The returned rows generate exactly the same submodule as the input rows, have
/// increasing leading columns, positive pivots, zeros below each pivot, and
/// residues above pivots reduced modulo the pivot. This gives
/// [`reduce_integer_vector`] a canonical quotient representative for
/// `Z^n / <rows>`.
fn normalize_relation_rows(mut rows: Vec<Vec<i128>>) -> Vec<Vec<i128>> {
    let width = rows.first().map_or(0, Vec::len);
    assert!(
        rows.iter().all(|r| r.len() == width),
        "integer relation rows must have equal width"
    );
    rows.retain(|r| !row_is_zero(r));
    let mut rank = 0usize;
    for col in 0..width {
        let Some(pivot) = (rank..rows.len()).find(|&r| rows[r][col] != 0) else {
            continue;
        };
        rows.swap(rank, pivot);
        if rows[rank][col] < 0 {
            negate_row(&mut rows[rank]);
        }

        loop {
            let Some(r) = ((rank + 1)..rows.len()).find(|&r| rows[r][col] != 0) else {
                break;
            };
            let pivot_val = rows[rank][col];
            let q = rows[r][col].div_euclid(pivot_val);
            let source = rows[rank].clone();
            sub_row_multiple(&mut rows[r], &source, q);
            if rows[r][col] != 0 && checked_abs(rows[r][col]) < checked_abs(rows[rank][col]) {
                rows.swap(rank, r);
                if rows[rank][col] < 0 {
                    negate_row(&mut rows[rank]);
                }
            }
        }

        if rows[rank][col] < 0 {
            negate_row(&mut rows[rank]);
        }
        let pivot_val = rows[rank][col];
        let source = rows[rank].clone();
        for r in 0..rows.len() {
            if r == rank || rows[r][col] == 0 {
                continue;
            }
            let q = rows[r][col].div_euclid(pivot_val);
            sub_row_multiple(&mut rows[r], &source, q);
        }
        rank += 1;
    }
    rows.retain(|r| !row_is_zero(r));
    rows.sort_by_key(|r| leading(r).unwrap_or(usize::MAX));
    rows
}

fn reduce_integer_vector(v: &mut [i128], rows: Vec<Vec<i128>>) {
    for row in normalize_relation_rows(rows) {
        let Some(lead) = leading(&row) else {
            continue;
        };
        let pivot = row[lead];
        debug_assert!(pivot > 0);
        let q = v[lead].div_euclid(pivot);
        if q != 0 {
            for i in 0..v.len() {
                v[i] -= q * row[i];
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exterior_algebra_lives_on_non_numbers() {
        // Generators that are NOT numbers — exactly where the Clifford/scalar story
        // cannot go — yet the quotient exterior algebra is well defined on them.
        let ext = GameExterior::new(vec![Game::star(), Game::up(), Game::switch(1, -1)]);
        assert!(!ext.game(0).is_number()); // ⋆
        assert!(!ext.game(1).is_number()); // ↑
        let (e0, e1) = (ext.generator(0), ext.generator(1));
        let alg = ext.algebra();
        // the wedge is antisymmetric and nonzero, but quotient-aware operations
        // still remember that it may carry torsion inherited from ⋆.
        let e01 = ext.wedge(&e0, &e1);
        assert!(!e01.is_zero());
        assert_eq!(e01, alg.scalar_mul(&Integer(-1), &alg.wedge(&e1, &e0)));
        assert!(alg.wedge(&e0, &e0).is_zero()); // e_i ∧ e_i = 0
    }

    #[test]
    fn grade1_is_the_game_group() {
        // Λ¹ → game group is a group homomorphism, recovering disjunctive sum.
        let ext = GameExterior::new(vec![Game::star(), Game::up()]);
        let (e0, e1) = (ext.generator(0), ext.generator(1));
        let alg = ext.algebra();
        // value(e0 + e1) = ⋆ + ↑
        let sum = alg.add(&e0, &e1);
        assert!(ext.value_of_grade1(&sum).eq(&Game::star().add(&Game::up())));
        // value(2·e0) = ⋆ + ⋆ = 0  (the 2-torsion of ⋆ shows up as a relation)
        let two_e0 = alg.scalar_mul(&Integer(2), &e0);
        assert!(ext.value_of_grade1(&two_e0).eq(&Game::zero()));
        // value(e0 − e1) = ⋆ − ↑
        let diff = alg.add(&e0, &alg.scalar_mul(&Integer(-1), &e1));
        assert!(ext
            .value_of_grade1(&diff)
            .eq(&Game::star().add(&Game::up().neg())));
    }

    #[test]
    fn game_relations_propagate_through_the_exterior_ideal() {
        let ext = GameExterior::new(vec![Game::star(), Game::up()]);
        assert!(ext.relations().iter().any(|r| r.coeffs == vec![2, 0]));
        let (star, up) = (ext.generator(0), ext.generator(1));
        let star_wedge_up = ext.wedge(&star, &up);
        assert!(!ext.is_zero(&star_wedge_up));
        assert!(ext.is_zero(&ext.scalar_mul(2, &star_wedge_up)));
    }

    #[test]
    fn duplicate_game_generators_are_quotiented_before_wedging() {
        let ext = GameExterior::new(vec![Game::star(), Game::star()]);
        assert!(ext
            .relations()
            .iter()
            .any(|r| r.coeffs == vec![1, -1] || r.coeffs == vec![-1, 1]));
        let e0 = ext.generator(0);
        let e1 = ext.generator(1);
        assert_eq!(ext.reduce(&e0), ext.reduce(&e1));
        assert!(ext.is_zero(&ext.wedge(&e0, &e1)));
    }

    #[test]
    fn integer_relation_reduction_uses_the_full_row_lattice() {
        let rows = vec![vec![2, 0], vec![3, 0]];
        assert_eq!(normalize_relation_rows(rows.clone()), vec![vec![1, 0]]);

        let mut v = vec![5, 7];
        reduce_integer_vector(&mut v, rows);
        assert_eq!(v, vec![0, 7]);
    }

    #[test]
    fn integer_relation_reduction_handles_coupled_relations() {
        let rows = vec![vec![2, 4], vec![6, 10]];
        let mut v = vec![8, 14]; // one copy of each relation
        reduce_integer_vector(&mut v, rows.clone());
        assert_eq!(v, vec![0, 0]);

        let mut shifted = vec![9, 14];
        reduce_integer_vector(&mut shifted, rows);
        assert_ne!(shifted, vec![0, 0]);
    }
}
